apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cheddar
spec:
  rules:
  - host: px.3.123.33.38.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: px-lighthouse
          servicePort: 80

